
name: Compile Action .NET Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'  

      - name: Restore Dependencies
        run: dotnet restore  

      - name: Build the Project
        run: dotnet build --configuration Release  

      - name: Run Tests
        run: dotnet test --configuration Release  

      - name: Publish the Project
        run: dotnet publish --configuration Release --output ./output  # Publish the project

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-output
          path: ./output 
